env:
  node: false
  browser: true
  commonjs: true
parserOptions:
  ecmaVersion: 5
globals:
  Promise: true
rules:
  no-bitwise: 2
  eqeqeq: 0
  guard-for-in: 2
  no-extend-native: 2
  no-use-before-define: 2
  no-caller: 2
  no-sequences: 2
  no-irregular-whitespace: 2
  no-new: 2
  strict:
    - 2
    - function
  no-undef: 2
  no-unused-vars: 2
  indent:
    - 2
    - 2
    - SwitchCase: 1
  one-var:
    - 2
    - never
